name = "msh_light"
license = "MIT"
description = ""
homepage = "https://www.cs.princeton.edu/~mhalber"
tags = []
features = []
min_version = 0.18
googleAnalytics = "UA-93944349-1"
disqusShortname = "XYW"
[author]
  name = "Maciej Halber"
  homepage = "https://www.cs.princeton.edu/~mhalber"

